### ISSUE TITLE
IPFS integration

### ISSUE THREAD

**Issue by FieldmanJR1** [near-ndc/voting-v2#5]
As a Product Manager I want to have snapshot in form of json file on IPFS

AC1: Snapshot is available for the block specified in the Election framework document

**Comment by akorchyn** [comment]
Uploaded. https://bafybeidy6aerzfcaytshbntccgq6oquopd4q3ftsuaz66bstjfc4vpuwku.ipfs.w3s.link
But can be re-created if review would introduce critical comments.

**Comment by akorchyn** [comment]
CID: bafybeidy6aerzfcaytshbntccgq6oquopd4q3ftsuaz66bstjfc4vpuwku
